github-username: mtao
github-reponame: nyu-intro-to-computer-science
  #url: https://cs.nyu.edu
  #baseurl: /courses/spring23/CSCI-UA.0101-009/
title: Introduction to Computer Science
section: CSCI-UA.0101-009
description: >
  A thorough course in computer science concepts, focused on object-oriented programming using the Java programming language.
copyright: GNU General Public License, Version 3
layouts_dir: theme/_layouts/
plugins:
  - jekyll-feed
#  - jekyll-github-metadata
  - jekyll-seo-tag
defaults:
  - scope:
      path: "content"
      type: pages
    values:
      layout: page
  - scope:
      path: "slides"
      type: pages
    values:
      layout: presentation
